name: Run DCE then build docker

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

permissions:
  contents: read

jobs:
  run:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout ROCKETSHIP repo
      uses: actions/checkout@v3
      with:
        repository: petmri/ROCKETSHIP
        ref: master
        path: ROCKETSHIP

    #- name: Set up Python 3.10
    #  uses: actions/setup-python@v3
    #  with:
    #    python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #    pip install flake8 pytest
        
        
   # - name: Lint with flake8
   #   run: |
   #     # stop the build if there are Python syntax errors or undefined names
   #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
   #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
   #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    #- name: Test with pytest
    #  run: |
    #    pytest

    #- name: Set up MATLAB
    #  uses: matlab-actions/setup-matlab@v1
        
    - name: Preprocess the data
      run:  ./preprocess_all.sh -d /media/network_mriphysics/USC-PPG/RUNNER_DATA -b -Z -m -c
      
    - name: Run DCE
      run:  ./DCE_all.sh -d /media/network_mriphysics/USC-PPG/RUNNER_DATA -b
    
    - name: Output logs
      run:  |
        cat /media/network_mriphysics/USC-PPG/RUNNER_DATA/preprocessing_log.txt
        cat /media/network_mriphysics/USC-PPG/RUNNER_DATA/dce_log.txt

    - name: Convert HTML to PDF
      run:  wkhtmltopdf --enable-local-file-access /media/network_mriphysics/USC-PPG/RUNNER_DATA/1101743_runner/1st_timepoint/giga_report.html /media/network_mriphysics/USC-PPG/RUNNER_DATA/1101743_runner/1st_timepoint/giga_report.pdf
      continue-on-error: true

    - name: Upload analysis results
      uses: actions/upload-artifact@v3
      with:
        name: HTML_report
        path: |
          /media/network_mriphysics/USC-PPG/RUNNER_DATA/1101743_runner/1st_timepoint/giga_report.html
          /media/network_mriphysics/USC-PPG/RUNNER_DATA/1101743_runner/1st_timepoint/figures/
          /media/network_mriphysics/USC-PPG/RUNNER_DATA/1101743_runner/1st_timepoint/giga_report.pdf
        retention-days: 7
        if-no-files-found: error

  docker:
    needs: run
    strategy:
      fail-fast: false
      matrix:
        release: [R2020a, R2020b, R2021a, R2021b, R2022a, R2022b, R2023a]

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    
    - name: Build Dockerfile
      id: docker_build
      run: |
        docker image prune -f
        docker build --build-arg MATLAB_RELEASE=${{ matrix.release }} . -t lsaca05/dce:${{ matrix.release }}-${{ steps.extract_branch.outputs.branch }}

    # - name: Run Docker
    #   if: ${{ matrix.release }} == "R2020a"
    #   run: |
    #     ./run_docker.sh
    #     exit

    # - name: Push to Docker Hub
    #   if: steps.docker_build.outcome == 'success'
    #   run: |
    #     docker push lsaca05/dce:${{ matrix.release }}-${{ steps.extract_branch.outputs.branch }}